default:
  custom_tcp_protocol_addr: ":7654" # 自定义tcp协议（透传）
  tcp_protocol_addr: ":7653" # 官方tcp协议
  mqtt:
    addr: "127.0.0.1:1883"
    username: "root"
    password: "root"
    qos: 0
    retain: false
  topic:
    subscribe: "topic"
    publish_raw_data: "device/attributes"
    subscribe_raw_data: "plugin/tcp/#"
    gateway_publish_raw_data: "gateway/attributes"
  api:
    custom_addr: "0.0.0.0:8000" # 提供给thingspanel-go的http服务
    self_addr: "localhost:8089" # 提供给thingspanel-go的http服务
  tp:
    http_addr: "http://127.0.0.1:9999" # 连接thingspanel-go,docker
production:
  custom_tcp_protocol_addr: "example.com:7654"
  tcp_protocol_addr: "example.com:7653"
  mqtt:
    addr: "example.com:1883"
    username: "user"
    password: "password"
    qos: 0
    retain: false
  topic:
    subscribe: "topic"
    publish_raw_data: "device/attributes"
    subscribe_raw_data: "plugin/tcp/#"